#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <objc/message.h>
#import <dlfcn.h>

static BOOL busy=NO;
static UIBarButtonItem *selButton;

static id Call(id o, NSString *n){ if(!o)return nil; SEL s=NSSelectorFromString(n); if(![o respondsToSelector:s])return nil; @try{return ((id(*)(id,SEL))objc_msgSend)(o,s);}@catch(NSException *e){return nil;} }
static id KVC(id o, NSArray *ks){ for(NSString *k in ks)@try{id v=[o valueForKey:k];if(v&&v!=NSNull.null)return v;}@catch(NSException *e){} return nil; }
static NSString *Str(id v){ if(!v||v==NSNull.null)return @""; if([v isKindOfClass:NSString.class])return v; if([v isKindOfClass:NSAttributedString.class])return [v string]?:@""; return [v description]?:@""; }
static NSArray *Arr(id v){ if([v isKindOfClass:NSArray.class])return v; if([v isKindOfClass:NSSet.class])return [v allObjects]; if([v isKindOfClass:NSOrderedSet.class])return [v array]; return nil; }
static BOOL NoteLike(id o){ if(!o)return NO; NSString *c=NSStringFromClass([o class]); return ([c containsString:@"Note"]&&![c containsString:@"Controller"]&&![c containsString:@"View"])||[o respondsToSelector:NSSelectorFromString(@"plaintext")]||[o respondsToSelector:NSSelectorFromString(@"noteIdentifier")]; }
static NSArray *NotesOnly(id v){ NSArray *a=Arr(v); if(!a&&NoteLike(v))a=@[v]; NSMutableArray *r=[NSMutableArray array]; for(id x in a)if(NoteLike(x))[r addObject:x]; return r; }

static UIWindow *KeyWindow(void){ for(UIScene *s in UIApplication.sharedApplication.connectedScenes)if(s.activationState==UISceneActivationStateForegroundActive&&[s isKindOfClass:UIWindowScene.class])for(UIWindow *w in ((UIWindowScene*)s).windows)if(w.isKeyWindow)return w; return UIApplication.sharedApplication.windows.firstObject; }
static UIViewController *Top(void){ UIViewController *v=KeyWindow().rootViewController; while(v){ if(v.presentedViewController){v=v.presentedViewController;continue;} if([v isKindOfClass:UINavigationController.class]){v=[(UINavigationController*)v visibleViewController];continue;} if([v isKindOfClass:UITabBarController.class]){v=[(UITabBarController*)v selectedViewController];continue;} break;} return v; }

static id Context(void){ dlopen("/System/Library/PrivateFrameworks/NotesShared.framework/NotesShared",RTLD_LAZY|RTLD_GLOBAL); Class c=NSClassFromString(@"ICNoteContext"); for(NSString *n in @[@"sharedContext",@"defaultContext",@"sharedNoteContext",@"noteContext"]){id x=Call(c,n);if(x)return x;} return nil; }
static NSArray *AllNotes(void){ id c=Context(); for(NSString *n in @[@"visibleNotes",@"allNotes",@"notes"]){NSArray *a=Arr(Call(c,n));if(a)return a;} return @[]; }

static NSArray *DirectSelected(id o){ for(NSString *n in @[@"selectedNotes",@"selectedNoteObjects",@"selectedObjects",@"selectedItems",@"notesSelectedForAction",@"selectedManagedObjects"]){NSArray *a=NotesOnly(Call(o,n));if(a.count)return a;} id v=KVC(o,@[@"selectedNotes",@"selectedNoteObjects",@"selectedObjects",@"selectedItems",@"notesSelectedForAction",@"selectedManagedObjects"]); return NotesOnly(v); }
static NSArray *SelectedInView(UIView *v){ NSMutableArray *r=[NSMutableArray array]; if([v isKindOfClass:UITableView.class])for(NSIndexPath *p in ((UITableView*)v).indexPathsForSelectedRows?:@[]){UITableViewCell *c=[(UITableView*)v cellForRowAtIndexPath:p];id n=KVC(c,@[@"note",@"representedNote",@"representedObject",@"object",@"item"]);if(NoteLike(n))[r addObject:n];} if([v isKindOfClass:UICollectionView.class])for(NSIndexPath *p in ((UICollectionView*)v).indexPathsForSelectedItems?:@[]){UICollectionViewCell *c=[(UICollectionView*)v cellForItemAtIndexPath:p];id n=KVC(c,@[@"note",@"representedNote",@"representedObject",@"object",@"item"]);if(NoteLike(n))[r addObject:n];} for(UIView *s in v.subviews)for(id n in SelectedInView(s))if(![r containsObject:n])[r addObject:n]; return r; }
static NSArray *SelectedInVC(UIViewController *v){ if(!v)return @[]; NSArray *a=DirectSelected(v);if(a.count)return a; for(UIViewController *c in v.childViewControllers){a=SelectedInVC(c);if(a.count)return a;} return SelectedInView(v.view); }
static NSArray *Selected(void){ return SelectedInVC(KeyWindow().rootViewController); }

static NSString *Date(id v){ if(![v isKindOfClass:NSDate.class])return Str(v); static NSISO8601DateFormatter *f; static dispatch_once_t once; dispatch_once(&once,^{f=[NSISO8601DateFormatter new];}); return [f stringFromDate:v]?:@""; }
static NSDictionary *Serialize(id n){ id title=Call(n,@"title")?:Call(n,@"displayTitle")?:KVC(n,@[@"title",@"title1",@"displayTitle"]); id body=Call(n,@"plaintext")?:Call(n,@"plainText")?:Call(n,@"contentAsPlainText")?:KVC(n,@[@"plaintext",@"plainText",@"summary",@"content"]); id created=Call(n,@"creationDate")?:KVC(n,@[@"creationDate",@"creationDate1"]); id modified=Call(n,@"modificationDate")?:KVC(n,@[@"modificationDate",@"modificationDate1"]); id ident=Call(n,@"identifier")?:Call(n,@"noteIdentifier")?:KVC(n,@[@"identifier",@"noteIdentifier",@"objectID"]); id folder=Call(n,@"folder")?:KVC(n,@[@"folder",@"noteContainer"]); id ft=Call(folder,@"title")?:Call(folder,@"name")?:KVC(folder,@[@"title",@"name"]); return @{@"title":Str(title),@"body":Str(body),@"created":Date(created),@"modified":Date(modified),@"identifier":Str(ident),@"folder":Str(ft)}; }
static void Alert(NSString *t,NSString *m){ dispatch_async(dispatch_get_main_queue(),^{UIViewController *v=Top();if(!v)return;UIAlertController *a=[UIAlertController alertControllerWithTitle:t message:m preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"好" style:UIAlertActionStyleDefault handler:nil]];[v presentViewController:a animated:YES completion:nil];}); }
static void Export(NSArray *notes,BOOL selected){ if(busy)return;if(!notes.count){Alert(@"没有可导出的备忘录",@"请先选择至少一条备忘录。");return;} busy=YES; dispatch_async(dispatch_get_global_queue(QOS_CLASS_USER_INITIATED,0),^{NSMutableArray *items=[NSMutableArray array];for(id n in notes)@autoreleasepool{[items addObject:Serialize(n)];} NSDictionary *root=@{@"format":@"Apple Notes Export",@"version":@2,@"scope":selected?@"selected":@"all",@"count":@(items.count),@"exportedAt":Date(NSDate.date),@"notes":items}; NSError *e=nil;NSData *d=[NSJSONSerialization dataWithJSONObject:root options:NSJSONWritingPrettyPrinted error:&e];NSDateFormatter *f=[NSDateFormatter new];f.dateFormat=@"yyyyMMdd-HHmmss";NSString *name=[NSString stringWithFormat:selected?@"AppleNotes-Selected-%@.json":@"AppleNotes-%@.json",[f stringFromDate:NSDate.date]];NSString *p=[NSTemporaryDirectory() stringByAppendingPathComponent:name];BOOL ok=d&&[d writeToFile:p options:NSDataWritingAtomic error:&e];dispatch_async(dispatch_get_main_queue(),^{busy=NO;if(!ok){Alert(@"导出失败",e.localizedDescription?:@"无法生成文件");return;}UIViewController *v=Top();UIActivityViewController *a=[[UIActivityViewController alloc]initWithActivityItems:@[[NSURL fileURLWithPath:p]] applicationActivities:nil];if(a.popoverPresentationController)a.popoverPresentationController.barButtonItem=selButton;[v presentViewController:a animated:YES completion:nil];});}); }

@interface NEHandler:NSObject
+(instancetype)shared;-(void)selected:(id)x;-(void)all:(id)x;
@end
@implementation NEHandler
+(instancetype)shared{static id x;static dispatch_once_t once;dispatch_once(&once,^{x=[self new];});return x;}-(void)selected:(id)x{Export(Selected(),YES);}-(void)all:(id)x{Export(AllNotes(),NO);}
@end

static void Update(void){ UIViewController *v=Top();if(!v)return;NSArray *s=Selected();UINavigationItem *n=v.navigationItem;if(s.count){if(!selButton)selButton=[[UIBarButtonItem alloc]initWithTitle:@"导出所选" style:UIBarButtonItemStylePlain target:NEHandler.shared action:@selector(selected:)];selButton.title=[NSString stringWithFormat:@"导出所选(%lu)",(unsigned long)s.count];NSMutableArray *a=[n.rightBarButtonItems mutableCopy]?:[NSMutableArray array];if(![a containsObject:selButton]){[a insertObject:selButton atIndex:0];n.rightBarButtonItems=a;}}else if(selButton){NSMutableArray *a=[n.rightBarButtonItems mutableCopy]?:[NSMutableArray array];if([a containsObject:selButton]){[a removeObject:selButton];n.rightBarButtonItems=a;}} }

__attribute__((constructor))static void Init(void){@autoreleasepool{if(![NSBundle.mainBundle.bundleIdentifier isEqualToString:@"com.apple.mobilenotes"])return;dlopen("/System/Library/PrivateFrameworks/NotesShared.framework/NotesShared",RTLD_LAZY|RTLD_GLOBAL);dispatch_async(dispatch_get_main_queue(),^{[NSTimer scheduledTimerWithTimeInterval:.4 repeats:YES block:^(__unused NSTimer *t){Update();}];});}}
